### ISSUE TITLE
Failed to load module

### ISSUE THREAD

**Issue by Mandarancio** [rokf/howl-love2d#3]
Hi,
After installing your bundle, howl complains that it attempts to index a nil value:

> Failed to load bundle in ~/.howl/bundles/howl-love2d: ~/.howl/bundles/howl-love2d/init.moon:28: attempt to index a nil value

What it could be?

Thank you, Martino

**Comment by rokf** [comment]
Temporary fix: `git clone https://github.com/rokf/howl-love2d love2d` so it gets cloned into a folder named `love2d` instead of `howl-love2d`. It doesn't like the name for some reason. I'll figure this out.

**Comment by rokf** [comment]
Will be fixed as soon as the Howl `bundle-dependencies` branch gets merged into `master`. With a simple `require_bundle('lua')` the LÖVE bundle will make sure that the Lua bundle is loaded before it and the issue will be gone :wink:

**Comment by rokf** [comment]
Should be fixed with 5b9db94a41ed5d31ae5be97c8861714a032976dc. **Master branch of Howl required.**
