### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by ghost** [rokf/howl-love2d#4]
I follow the instruction: `cd ~/.howl/bundles` and there is no `bundles` directory, so I create it, then cd and clone repo. After this i launch howl (0.5.1), open some main.lua file from my love2d-project and nothing changes. `love` is still unknown variable. The bundle is not loaded. I tried to press alt-x, enter command `bundle-load` and there is no items to load.

**UPD** Sorry, bundle is loaded! I can use autocomplete by pressing ctrl+space after "love.", but why all `love` variables marked as errors ('mutating non-standard global variable')?

**Comment by rokf** [comment]
Because they're not white-listed in linter. I'll ask if I can do something about that ;)

**Comment by ghost** [comment]
Thank you :)

**Comment by rokf** [comment]
@Winterwolf Put a file named `.luacheckrc` inside your project and put the text `globals = { "love" }
` into that file. This is a configuration file for `luacheck`. It won't bark at you anymore :smile:
